# Generated by Django 4.1.1 on 2022-09-16 16:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first name', max_length=30, validators=[django.core.validators.MinLengthValidator(3, 'First name can not be less than 3 symbols ')], verbose_name='Имя')),
                ('last_name', models.CharField(db_column='last name', max_length=30, validators=[django.core.validators.MinLengthValidator(3, 'Last name can not be less than 3 symbols')], verbose_name='Фамилия')),
                ('birthday', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
            ],
        ),
    ]
